apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - name: employee-service
        image: employee-service-image:latest
        ports:
        - containerPort: 8080
