apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: development
spec:
  selector:
    app: employee-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
